### PR TITLE
Bump ChunkSplitters to 3.0

### PR DESCRIPTION
**Pull request by henry2004y**
ChunkSplitters.jl 3.0 introduces a breaking change to the `chunks` API, where `n` (the number of chunks) is now a keyword parameter.

### CODE REVIEW

**Comment by DanielVandH** [comment]
Thanks for this. I forgot there was a new release for that package. From https://github.com/JuliaFolds2/ChunkSplitters.jl/blob/main/CHANGELOG.md, I think instead the fix is to change `chunks` to `index_chunks` instead? `chunks` is a different function now apparently...

**Comment by henry2004y** [comment]
> Thanks for this. I forgot there was a new release for that package. From https://github.com/JuliaFolds2/ChunkSplitters.jl/blob/main/CHANGELOG.md, I think instead the fix is to change `chunks` to `index_chunks` instead? `chunks` is a different function now apparently...

Yeah you are right, I forgot about that. Maybe in some places where the indices are not needed, we can simply use `chunks`.

**Comment by DanielVandH** [comment]
Do they fail with v2?

**Comment by henry2004y** [comment]
OK, I now understand the issue. We need to add `enumerate` as well as switching the order of indices and values. Actually the new way follows the natural argument order returned from `enumerate`, which is good.

**Comment by DanielVandH** [comment]
Thanks for looking into this! I appreciate it. If you can remove the vscode settings file and bump the package version I'll merge and make a new release

**Comment by DanielVandH** [comment]
> I didn't run the tests on my laptop because it took quite a while :)

And yeah they take a bit of time unfortunately, sorry about that.. probably longer than is needed but back when I was first developing the package it helped to be a bit exhaustive 😅

**Comment by DanielVandH** [comment]
New version has now been released. Thanks @henry2004y!

**Pull request merged**
